# Generated by Django 5.0.3 on 2024-04-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('letter', models.CharField(max_length=9)),
                ('position', models.IntegerField()),
                ('seo_description', models.CharField(max_length=200)),
                ('seo_title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('seo_description_en', models.CharField(max_length=200)),
                ('seo_description_ru', models.CharField(max_length=200)),
                ('seo_description_uz', models.CharField(max_length=200)),
                ('seo_title_en', models.CharField(max_length=200)),
                ('seo_title_ru', models.CharField(max_length=200)),
                ('seo_title_uz', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('is_main', models.BooleanField()),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('is_top', models.BooleanField()),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('price', models.FloatField()),
                ('seo_description_en', models.CharField(max_length=200)),
                ('seo_description_ru', models.CharField(max_length=200)),
                ('seo_description_uz', models.CharField(max_length=200)),
                ('seo_title_en', models.CharField(max_length=200)),
                ('seo_title_ru', models.CharField(max_length=200)),
                ('seo_title_uz', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to='product/')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('file', models.ImageField(upload_to='product/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
