# Generated by Django 5.0.1 on 2024-04-03 19:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Kodni kiritishlar soni:')),
                ('validated', models.BooleanField(default=False, help_text='Shaxsiy kabinetingizni yaratishingiz mumkin!')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('verify_code', models.SmallIntegerField(unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('step_reset', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=10, null=True)),
                ('step_change_phone', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('card', models.IntegerField(null=True)),
                ('card_info', models.CharField(max_length=4, null=True)),
                ('password', models.CharField(max_length=200)),
                ('paspord_raqam', models.CharField(max_length=6, null=True)),
                ('paspord_seria', models.CharField(max_length=3, null=True)),
                ('paspord', models.ImageField(null=True, upload_to='pasportlar/')),
                ('image', models.ImageField(null=True, upload_to='rasmlar/')),
                ('adress', models.TextField(null=True)),
                ('viloyat', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Sirdaryo', 'Sirdaryo'), ('Namangan', 'Namangan'), ("Farg'ona", "Farg'ona"), ('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Nukus', 'Nukus')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
