# Generated by Django 5.0.3 on 2024-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
